### PR TITLE
Loongarch workflow

### PR DESCRIPTION
**Pull request by fengyuentau**

### CODE REVIEW

**Comment by fengyuentau** [comment]
https://github.com/opencv/ci-gha-workflow/actions/runs/7738406020/job/21099145639?pr=139#step:12:559

GitHub Actions do work natively on the loongarch64 server.

**Comment by asmorkalov** [comment]
```
[ RUN      ] DivPerfTestFluid/DivPerfTest.TestPerformance/2, where GetParam() = (compare_f, 128x128, 8UC1, 2, 2.3, { gapi.kernel_package })
AbsExact error: G-API output and reference output matrixes are not bitexact equal.
/home/opencv-cn/GHA-OCV-1/_work/ci-gha-workflow/ci-gha-workflow/opencv/modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp:464: Failure
Value of: cmpF(out_mat_gapi, out_mat_ocv)
  Actual: false
Expected: true
```
Looks like accuracy issue

**Comment by fengyuentau** [comment]
I asked loongson devs for help and they should be available to fix these issues after the Chinese Spring Festival holiday (ends on Feb 18).
________________________________
发件人: Alexander Smorkalov ***@***.***>
发送时间: Thursday, February 1, 2024 7:28:00 PM
收件人: opencv/ci-gha-workflow ***@***.***>
抄送: Yuantao Feng ***@***.***>; Author ***@***.***>
主题: Re: [opencv/ci-gha-workflow] Loongarch workflow (PR #139)


[ RUN      ] DivPerfTestFluid/DivPerfTest.TestPerformance/2, where GetParam() = (compare_f, 128x128, 8UC1, 2, 2.3, { gapi.kernel_package })
AbsExact error: G-API output and reference output matrixes are not bitexact equal.
/home/opencv-cn/GHA-OCV-1/_work/ci-gha-workflow/ci-gha-workflow/opencv/modules/gapi/perf/common/gapi_core_perf_tests_inl.hpp:464: Failure
Value of: cmpF(out_mat_gapi, out_mat_ocv)
  Actual: false
Expected: true


Looks like accuracy issue

―

**Comment by asmorkalov** [comment]
I propose to disable the test for now with --gtest_filter and merge the pipeline. Also, do you use docker for it? I recommend to do so.

**Comment by fengyuentau** [comment]
They do have docker with quay-like image hosting site. However, I don't have the account to upload image on their site yet.

1. quay-like host: https://cr.loongnix.cn/search
2. manual: https://docs.loongnix.cn/loongnix/cloud/quay/manual.html

---

I will disable failed tests later today. Lets merge it for now then.

**Pull request merged**
