### PR TITLE
Added CI pipeline with openEuler22.03.SP2 and Ascend310

### PR DESCRIPTION
**Pull request by hipudding**
Base image: https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/24

Added CI pipeline with openEuler22.03.SP2 and Ascend310

### CODE REVIEW

**Comment by fengyuentau** [comment]
Let me connect the machine first. In the meantime, I propose to remove the if condition `    if: contains(github.event.pull_request.labels.*.name, 'category:cann')
` here but add it back when we add this workflow to the main repo.

**Comment by hipudding** [comment]
> Let me connect the machine first. In the meantime, I propose to remove the if condition ` if: contains(github.event.pull_request.labels.*.name, 'category:cann')` here but add it back when we add this workflow to the main repo.

The condition is removed temporarily.

**Comment by fengyuentau** [comment]
I mean we dont need this in this workflow, but put the if condition in the main repo's workflow file just like cuda does:

https://github.com/opencv/opencv/blob/b3791dc4be1c8b7159d6d68e9efe5cf63494d9ae/.github/workflows/PR-4.x.yaml#L24-L26

**Comment by hipudding** [comment]
> I mean we dont need this in this workflow, but put the if condition in the main repo's workflow file just like cuda does:
> 
> https://github.com/opencv/opencv/blob/b3791dc4be1c8b7159d6d68e9efe5cf63494d9ae/.github/workflows/PR-4.x.yaml#L24-L26

Oh, sure. Done.

**Comment by hipudding** [comment]
@fengyuentau Is CI machine ready for use now? If ready, please re-trigger this workflow, thanks.

**Comment by fengyuentau** [comment]
We are going to make the connection this afternoon. I will trigger the worflow after that.

**Comment by fengyuentau** [comment]
One runner is connected. Lets try run the workflow.

**Comment by hipudding** [comment]
> One runner is connected. Lets try run the workflow.

Because Cannops module has not been merged. It will not find opencv_test_cannops, and this workflow may fail.

**Comment by fengyuentau** [comment]
Ok, lets see whether the runner can pick up the job then.

**Comment by fengyuentau** [comment]
It is now running in progress. Connection is fixed.

**Comment by fengyuentau** [comment]
@asmorkalov Could you also review the workflow? The workflow is mainly for testing `cannops` in https://github.com/opencv/opencv_contrib/pull/3552.

**Comment by fengyuentau** [comment]
What about only testing the `cannops` module in this workflow? In this case, we just need to build the `cannops` module, for example,

```
$ cmake --build build --target opencv_test_cannops
```

So we do not need to wait for the bug fix to merge this workflow.

**Comment by hipudding** [comment]
> What about only testing the `cannops` module in this workflow? In this case, we just need to build the `cannops` module, for example,
> 
> ```
> $ cmake --build build --target opencv_test_cannops
> ```
> 
> So we do not need to wait for the bug fix to merge this workflow.

Of course. Let me push a new commit to add target when building.

**Comment by hipudding** [comment]
@fengyuentau  The workflow failed again. Because cannops module has not merged yet.
But I tried this workflow in my local vm, it works. Can it merge and tested with PR https://github.com/opencv/opencv_contrib/pull/3552?

**Comment by fengyuentau** [comment]
@asmorkalov Do you have comments on this workflow? If no, I propose to merge.

**Comment by hipudding** [comment]
@asmorkalov Good day. I would like to know if you have any comments for this PR. If there's not any, could you please merge this workflow? I'd like to test it with Cannops module(https://github.com/opencv/opencv_contrib/pull/3552).

**Comment by fengyuentau** [comment]
Oops

**Comment by hipudding** [comment]
> Oops

Since the bugfix has merged. Should I revert last commit and compile all the target?

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
