### PR TITLE
Enable c++11 on macOS ARM64 and x86_64 by default

### PR DESCRIPTION
**Pull request by asenyaev**
This PR fixes an issue which happens from time to time on macOS ARM64 and x86_64, when C++ standard is not defined, but a compiler uses c++98 in this case. You can configure it inside Xcode or writing `-std=c++11` 

Links with c++11 standard:
- https://github.com/opencv/ci-gha-workflow/runs/7237268262?check_suite_focus=true#step:11:530
- https://github.com/opencv/ci-gha-workflow/runs/7237268949?check_suite_focus=true#step:10:570

Links with unexpected behavior:
- https://github.com/opencv/ci-gha-workflow/runs/7347563133?check_suite_focus=true#step:11:31
- https://github.com/opencv/ci-gha-workflow/runs/7342549234?check_suite_focus=true#step:10:29

### CODE REVIEW

**Comment by fengyuentau** [comment]
Did you find the reason why this issue happens?

**Comment by asenyaev** [comment]
No, I cannot reproduce it locally, but it happens in CI from time to time. In addition, I see that any Contrib builds use `c++11` standard by default, the issue happens only with OpenCV builds.

**Review by fengyuentau — APPROVED** [review]

**Comment by asenyaev** [comment]
I'm not sure about `c++11` for OpenCV Contrib 3.4 branch, there are a lot of warnings after this change.

Part of a log file:
```
364/2567] Building CXX object 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/div.cpp.o
/Users/opencv-cn/GHA-OCV-1/_work/ci-gha-workflow/ci-gha-workflow/opencv/3rdparty/carotene/src/div.cpp:93:19: warning: unused function 'divSaturate<__attribute__((neon_vector_type(2))) unsigned int>' [-Wunused-function]
inline uint32x2_t divSaturate<uint32x2_t>(const uint32x2_t &v1, const uint32x2_t &v2, const float scale)
                  ^
/Users/opencv-cn/GHA-OCV-1/_work/ci-gha-workflow/ci-gha-workflow/opencv/3rdparty/carotene/src/div.cpp:122:19: warning: unused function 'divWrap<__attribute__((neon_vector_type(2))) unsigned int>' [-Wunused-function]
inline uint32x2_t divWrap<uint32x2_t>(const uint32x2_t &v1, const uint32x2_t &v2, const float scale)
                  ^
/Users/opencv-cn/GHA-OCV-1/_work/ci-gha-workflow/ci-gha-workflow/opencv/3rdparty/carotene/src/div.cpp:127:20: warning: unused function 'vtstq' [-Wunused-function]
inline  uint32x4_t vtstq(const uint32x4_t  & v0, const uint32x4_t  & v1) { return vtstq_u32(v0, v1); }
                   ^
/Users/opencv-cn/GHA-OCV-1/_work/ci-gha-workflow/ci-gha-workflow/opencv/3rdparty/carotene/src/div.cpp:134:20: warning: unused function 'vtst' [-Wunused-function]
inline  uint32x2_t vtst(const uint32x2_t  & v0, const uint32x2_t  & v1) { return vtst_u32(v0, v1); }
                   ^
/Users/opencv-cn/GHA-OCV-1/_work/ci-gha-workflow/ci-gha-workflow/opencv/3rdparty/carotene/src/div.cpp:270:19: warning: unused function 'recipSaturate<__attribute__((neon_vector_type(2))) unsigned int>' [-Wunused-function]
inline uint32x2_t recipSaturate<uint32x2_t>(const uint32x2_t &v2, const float scale)
                  ^
/Users/opencv-cn/GHA-OCV-1/_work/ci-gha-workflow/ci-gha-workflow/opencv/3rdparty/carotene/src/div.cpp:297:19: warning: unused function 'recipWrap<__attribute__((neon_vector_type(2))) unsigned int>' [-Wunused-function]
inline uint32x2_t recipWrap<uint32x2_t>(const uint32x2_t &v2, const float scale)
                  ^
6 warnings generated.
```

**Comment by asenyaev** [comment]
Closing this, because we've discussed not to force enable C++11 and to fix issues which happen only on macOS ARM64. The fix is in https://github.com/opencv/opencv/pull/22412

**Pull request closed without merging**
