### PR TITLE
Update openEuler image tag

### PR DESCRIPTION
**Pull request by hipudding**

### CODE REVIEW

**Comment by fengyuentau** [comment]
Has the dependent PR merged yet?

**Comment by fengyuentau** [comment]
Merge this after https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/28/files#diff-d139e503934c4264e7462305bdd2e0adf873ca72ce783b24ba3f61ebfea67447R1

**Comment by fengyuentau** [comment]
>   Error response from daemon: manifest for quay.io/opencv-ci/opencv-openeuler-22.03.sp2-ascend310:20240220 not found

@asmorkalov Could you trigger a build on the new image? I just merged https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/28.

**Comment by asmorkalov** [comment]
@fengyuentau I built the image. CI passed. Go head with the patch.

**Review by fengyuentau — APPROVED** [review]
Thank you!

**Pull request merged**
