### PR TITLE
Warnings handling on Linux

### PR DESCRIPTION
**Pull request by asenyaev**
Depends on https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/7.

### CODE REVIEW

**Comment by fengyuentau** [comment]
There is a warning `WARNING: Error loading config file: /root/.docker/config.json: stat /root/.docker/config.json: permission denied` only happens on `ARM64` which seems to be related to docker thing.

**Comment by asenyaev** [comment]
I agree with you.

For the docker warning, it should be fixed after moving from root to ci user, and this won't be in a log file, because it happens in the beginning of each step.

**Comment by alalek** [comment]
All these configurations (starting from Ubuntu 20.04) are new (if we comparing with BuildBot-based CI).
Before adding of new configuration we usually eliminate all configuration issues including build warnings, test failures, etc
The similar step with source code preparation should be done in this case too.

**Comment by alalek** [comment]
No, we should not fix just CI.
We should fix default builds on users systems.

The right way is:
- determine which GCC version brings this regression
- adopt CMake scripts to suppress this warning or add `#pragma` into source code.

**Comment by asenyaev** [comment]
Added `#pragma` it in https://github.com/opencv/opencv/pull/22246

**Comment by asmorkalov** [comment]
LGTM to me. Please rebase and fix conflicts.

**Pull request merged**
