### PR TITLE
Test PRs in debug mode to check build and generic not optimized branches

### PR DESCRIPTION
**Pull request by asmorkalov**
Build for ARM without NEON and other optimizations. Perf tests and extended DNN tests are disabled to save time.

### CODE REVIEW

**Comment by asmorkalov** [comment]
@fengyuentau Please take a look on the PR.

**Comment by fengyuentau** [comment]
Does this workflow intend to be triggered for each single pull request? I am afraid of our limited computing resources.

**Comment by asmorkalov** [comment]
Yes, I want to catch NEON/AVX related issues like the regression with Winograd. Let reduce testing scope for debug pipeline to reduce execution time.

**Review by fengyuentau — APPROVED** [review]
We can merge and get it working to see whether our computing resources satisfy our needs.

**Pull request merged**
