### PR TITLE
Added CI pipeline with OpenVINO.

### PR DESCRIPTION
**Pull request by asmorkalov**
Environment: https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/19

### CODE REVIEW

**Comment by asmorkalov** [comment]
Blocker: https://github.com/opencv/opencv/issues/24051

**Comment by dkurt** [comment]
```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] Test_Darknet_layers.region/0, where GetParam() = NGRAPH/CPU
[  FAILED  ] DNNTestHighLevelAPI.predict/0, where GetParam() = CPU
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_dropout_default_ratio_NGRAPH_CPU, where GetParam() = (test_dropout_default_ratio, NGRAPH/CPU)
```

**Comment by dkurt** [comment]
@asmorkalov, remaining problem is about missed `age-gender-recognition-retail-0013.xml` file:
```
C++ exception with description "OpenCV(4.8.0-dev) /home/openvino/opencv/modules/ts/src/ts.cpp:1071: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml in function 'findData'
```

**Comment by asmorkalov** [comment]
Yes, @TolyaTalamanov works on it.

**Comment by dkurt** [comment]
There are two options: make file optional or download to CI system. Seems like it's just missed:
https://github.com/opencv/opencv/blob/0245c0cd10387f2de7c7bd076585a285d977e53c/modules/dnn/test/test_ie_models.cpp#L104-L106

**Comment by dkurt** [comment]
Any progress here? Just for reference, direct links are https://storage.openvinotoolkit.org/repositories/open_model_zoo/2023.0/models_bin/1/age-gender-recognition-retail-0013/FP32/. I can add them as a part of https://github.com/opencv/opencv_extra/pull/1080.

**Comment by asmorkalov** [comment]
@dkurt you are welcome. @TolyaTalamanov promised to do it, but he is on vacation now.

**Comment by dkurt** [comment]
@asmorkalov, please re-run action to check fixes on latest 4.x branch.

**Comment by dkurt** [comment]
@asmorkalov, reminder. Now tests expect to pass. I made some changes to 4.x branch.

**Comment by dkurt** [comment]
@asmorkalov, checks passed :tada:

**Comment by asmorkalov** [comment]
@dkurt @mshabunin please review and approve.

**Review by dkurt — APPROVED** [review]

**Review by mshabunin — APPROVED** [review]

**Pull request merged**
